# Mise configuration for Auth service
[settings]
experimental = true
quiet = true

[shell_alias]
r = "mise run"

[vars]
CONTRACTS_DIR = "{{config_root}}/../../contracts"

[tasks.generate]
description = "Generate code from protobuf definitions"
run = """
  #!/usr/bin/env bash
  set -euo pipefail
  cd {{vars.CONTRACTS_DIR}}
  buf generate --template buf.gen.auth.yaml
  """

# Database tasks
[tasks."db:migrate:build"]
description = "Build the database migrations (needed to embed go migrations)"
# sources = ["cmd/migration/*.go", "{{config_root}}/internal/infra/persistence/migrations/scripts/*.go"]
run = """
  go build -o ${BUILD_DIR}/ cmd/migration/migrate.go &&
  ls -l ${BUILD_DIR}/migrate
"""

[tasks."db:migrate:up"]
# depends = ["db:migrate:build"]
description = "Run database migrations up"
run = "go run cmd/migration/*.go up"

[tasks."db:migrate:down"]
depends = ["db:migrate:build"]
description = "Run database migrations down"
run = "${BUILD_DIR}/migrate down"

[tasks."db:migrate:create"]
description = "Create new SQL/Go migration"
run = "go run cmd/migration/*.go create -d {{vars.MIGRATIONS_DIR}}"

[tasks."db:migrate:version"]
description = "Show current migration version"
run = "go run cmd/migration/*.go version"

[tasks."db:migrate:fix"]
description = "Fix the order of migrations"
run = "go run cmd/migration/*.go fix"

[tasks."db:migrate:reset"]
description = "Down all the migrations"
run = "go run cmd/migration/*.go reset"

[tasks."db:migrate:status"]
description = "Show current migration statud"
run = "go run cmd/migration/*.go status"
